In [2]:
# prompt: import employee_attrition_sample dataset and create a dataframe as df


import pandas as pd
df = pd.read_csv('ds.csv')
df.head()

,EmployeeID,Age,Gender,MaritalStatus,Dependents,JobRole,Department,Tenure,Salary,Bonus,...,ManagerSatisfaction,TeamCohesion,CareerGrowthOpportunity,LearningOpportunities,JobSatisfaction,WorkLifeBalance,PerformanceRating,RemoteWork,CommuteTime,Attrition
0,1,50,Male,Single,0,Analyst,Finance,4.8,91813,0,...,1,5,5,2,1,3,2,No,50,Yes
1,2,36,Male,Married,3,Manager,Sales,5.3,57712,5000,...,2,2,5,1,5,2,5,No,19,No
2,3,29,Male,Married,0,Manager,Finance,10.3,38415,10000,...,5,3,3,5,2,1,5,No,48,Yes
3,4,42,Male,Divorced,3,Manager,Sales,11.4,92292,10000,...,3,3,2,1,2,2,4,Yes,53,No
4,5,40,Female,Married,0,Engineer,Sales,12.0,53833,15000,...,4,3,1,2,1,1,2,Yes,79,No

In [4]:
# prompt: create an attrition prediction model using Age Tenure and Salary from dataframe df

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Assuming 'Attrition' is the target variable in your DataFrame
# and it's a binary classification problem (e.g., 0 for No Attrition, 1 for Attrition)

# Select features and target
features = ['Age', 'Tenure', 'Salary'] # Replace 'Salary' with the actual column name for Salary
target = 'Attrition' # Replace 'Attrition' with the actual column name for Attrition

# Handle potential missing values (simple imputation for demonstration)
# You might want to use more sophisticated methods depending on your data
df = df.dropna(subset=[target] + features)

# Convert categorical features to dummy variables if they exist and are not numerical
# In this case, Age, Tenure, and Salary are likely numerical, but this is good practice
# df = pd.get_dummies(df, columns=['CategoricalColumn1', 'CategoricalColumn2'], drop_first=True)


X = df[features]
y = df[target]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Random Forest Classifier model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy}")

Model Accuracy: 0.6